import { invoke } from "@tauri-apps/api/core";

export const api = {
  getSettings: () => invoke("get_settings") as Promise<any>,
  saveSettings: (newSettings: any) => invoke("save_settings", { newSettings }) as Promise<any>,
  scan: () => invoke("scan") as Promise<any>,
  getMovies: () => invoke("get_movies") as Promise<any>,
  search: (query: string, year?: number) => invoke("search", { query, year: year ?? null }) as Promise<any>,
  getMovieDetails: (tmdbId: number) => invoke("movie_details", { tmdbId }) as Promise<any>,
  matchMovie: (movieId: string, tmdbId: number) => invoke("process_movie", { movieId, tmdbId }) as Promise<any>,
  saveNfo: (movieId: string) => invoke("save_nfo_cmd", { movieId }) as Promise<any>,
  downloadImages: (movieId: string) => invoke("download_images_cmd", { movieId }) as Promise<any>,
  processMovie: (movieId: string, tmdbId: number) => invoke("process_movie", { movieId, tmdbId }) as Promise<any>,
  autoMatch: () => invoke("auto_match") as Promise<any>,
  ignoreMovie: (movieId: string, ignored: boolean = true) => invoke("ignore_movie", { movieId, ignored }) as Promise<any>,
  imdbSearch: (query: string, year?: number) => invoke("imdb_search_cmd", { query, year: year ?? null }) as Promise<any>,
  imdbProcess: (movieId: string, imdbId: string) => invoke("imdb_process", { movieId, imdbId }) as Promise<any>,
  getMovieImages: (movieId: string) => invoke("get_movie_images", { movieId }) as Promise<any>,
  saveImage: (movieId: string, imageUrl: string, imageType: "poster" | "fanart") => invoke("save_image_cmd", { movieId, imageUrl, imageType }) as Promise<any>,
  unsetMovie: (movieId: string) => invoke("unset_movie", { movieId }) as Promise<any>,
  getDuplicates: () => invoke("get_duplicates") as Promise<any>,
  deleteMovieFile: (movieId: string) => invoke("delete_movie_file", { movieId }) as Promise<any>,
  probeAll: () => invoke("probe_all") as Promise<any>,
  deleteImage: (movieId: string, imageType: "poster" | "fanart") => invoke("delete_image_cmd", { movieId, imageType }) as Promise<any>,
  setIgnoredDuplicateGroups: (groups: string[]) => invoke("set_ignored_duplicate_groups", { groups }) as Promise<any>,
};
